service:
  name: photos-catalogue-app

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true


provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    CATALOGUE_TABLE: Catalogue-${self:provider.stage}
    AUTH_0_SECRET: A9p7GzOkccWoKdRWDWhCpqFL7eIncgCw5hi-dsbkEcL6PHAi9AYhSJonfXIJzt_n
    IMAGES_S3_BUCKET: catalogueApp-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
  
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  CreateCatalogue:
    handler: src/lambda/http/createCatalogue.handler
    events:
      - http:
          method: post
          path: catalogue
          cors: true
          authorizer: Auth
    iamRoleStatementsName: ${self:service.name}-createCatalogue-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATALOGUE_TABLE}

  GetCatalogues:
    handler: src/lambda/http/getCatalogues.handler
    events:
      - http:
          method: get
          path: catalogue
          cors: true
    iamRoleStatementsName: ${self:service.name}-getCatalogue-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATALOGUE_TABLE}

  DeleteCatalogue:
    handler: src/lambda/http/deleteCatalogue.handler
    events: 
      - http:
          method: delete
          path: catalogue/{catalogueId}
          cors: true
    iamRoleStatementsName: ${self:service.name}-deleteCatalogue-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem 
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATALOGUE_TABLE}

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{catalogueId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatementsName: ${self:service.name}-generateUploadUrl-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATALOGUE_TABLE}
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*

        
resources:
  Resources:
    CatalogueDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: catalogueId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: catalogueId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CATALOGUE_TABLE}
    

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
